version: '3'
services:

  api:
    build: ./p_menu
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./p_menu:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  frontend:
    build: ./frontend/menu/
    volumes: 
      - ./frontend/menu/:/frontend/menu/
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://34.176.59.69
    depends_on:
      - db
      - api
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - type: bind
  #       source: nginx.conf
  #       target: /etc/nginx/nginx.conf
  #   depends_on:
  #     - api
  #     - frontend
volumes:
  postgres_data: