version: '3'
services:

  api:
    build: ./p_menu
    command: "sh -c gunicorn p_menu.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./p_menu:/code
    ports:
      - "8000:80"
    depends_on:
      - db
  
  frontend:
    build: ./frontend/menu/
    volumes: 
      - ./frontend/menu/:/frontend/menu/
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://127.0.0.1:8000
    depends_on:
      - db
      - api
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
volumes:
  postgres_data: