apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  #replicas: 3
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: menu-api
        image: adolfoarmas90/menu_api:latest
        env: 
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: CLOUD_NAME
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: API_KEY
          - name: API_SECRET
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: API_SECRET
        ports:
        - containerPort: 8000