apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: django
      role: api
      tier: backend
  template:
    metadata:
      labels:
        app: django
        role: api
        tier: backend
    spec:
      volumes:
        - name: django-app-data
          persistentVolumeClaim:
            claimName: django-app-pvc
      containers:
        - name: django
          image: adolfoarmas90/menu_api:79
          env: 
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: CLOUD_NAME
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: API_KEY
          - name: API_SECRET
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: API_SECRET

          volumeMounts:
              - name: django-app-data
                mountPath: /vol/web

        - name: proxy
          image: adolfoarmas90/proxy:79
          ports:
            - containerPort: 8000
              name: proxy
          volumeMounts:
            - name: django-app-data
              mountPath: /vol/web
          env:
            - name: APP_HOST
              value: '127.0.0.1'
            - name: APP_PORT
              value: '8080'