apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  #replicas: 3
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: menu-frontend
        image: adolfoarmas90/menu_frontend:48
        env:
          - name: REACT_APP_API_URL
            value: http://api:8000
        ports:
        - containerPort: 80

