apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
    role: api
    tier: backend
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    role: db
  ports:
  - name: db
    port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    role: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80